# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 21:35
from __future__ import unicode_literals

import apps.student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indetify_attendant', models.CharField(max_length=20)),
                ('name_attendat', models.CharField(max_length=30)),
                ('lastname_attendat', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('address_attendant', models.CharField(max_length=60)),
                ('relationship', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Abuelo(a)', 'Abuelo(a)'), ('Tio(a)', 'Tio(a)'), ('Hermano(a)', 'Hermano(a)')], max_length=20)),
                ('number_telephone', models.CharField(blank=True, max_length=40)),
                ('number_cellphone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Documenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documet_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips_assigned', models.CharField(blank=True, max_length=50)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuepayments', models.IntegerField()),
                ('datepayment', models.DateField()),
                ('paymentmethod', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Cheque', 'Cheque')], max_length=30)),
                ('checknumber', models.CharField(blank=True, max_length=30)),
                ('observations', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paymentsconcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentsconcepts', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Socioeconomic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesisben', models.CharField(blank=True, max_length=10)),
                ('scoresisben', models.FloatField(blank=True)),
                ('stratum', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('code_student', models.AutoField(default=apps.student.models.random_id, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name_student', models.CharField(max_length=50)),
                ('lastname_student', models.CharField(max_length=50)),
                ('number_document', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=30)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('neighborhood', models.CharField(max_length=50)),
                ('number_telephone', models.CharField(max_length=40)),
                ('cellphone_number', models.CharField(max_length=40)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.City')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Documenttype')),
            ],
        ),
        migrations.AddField(
            model_name='socioeconomic',
            name='code_student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='payments',
            name='code_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='payments',
            name='paymentsconcepts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Paymentsconcepts'),
        ),
        migrations.AddField(
            model_name='health',
            name='code_student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='health',
            name='eps_affiliate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.Eps'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='code_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
