# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code_student',
            field=models.AutoField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
