# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomic',
            name='scoresisben',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomic',
            name='stratum',
            field=models.CharField(choices=[('0', '0'), ('1', 'Estrato 1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2),
        ),
    ]
