# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180811_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socioeconomic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesisben', models.CharField(blank=True, max_length=10)),
                ('scoresisben', models.FloatField(blank=True)),
                ('stratum', models.CharField(max_length=10)),
                ('code_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
